//! nginx configuration generation for local webspaces.

use uuid::Uuid;

/// Generate an nginx server block config for a webspace.
pub fn generate_config(webspace_id: Uuid, domains: &[String], port: u16) -> Result<(), String> {
    let server_names = domains.join(" ");
    let config = format!(
        r#"# Auto-generated by web-agency for webspace {webspace_id}
server {{
    listen 443 ssl http2;
    server_name {server_names};

    ssl_certificate /etc/letsencrypt/live/{first}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{first}/privkey.pem;

    location / {{
        proxy_pass http://127.0.0.1:{port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}
}}
"#,
        first = domains.first().unwrap_or(&"localhost".to_string()),
    );

    // STUB: In production, write to /etc/nginx/sites-enabled/ and reload nginx
    tracing::info!(
        "STUB: would write nginx config for webspace {webspace_id} ({} domains, port {port}):\n{config}",
        domains.len()
    );
    Ok(())
}

/// Remove nginx config for a webspace.
pub fn remove_config(webspace_id: Uuid) -> Result<(), String> {
    // STUB: remove /etc/nginx/sites-enabled/webspace-{id}.conf and reload
    tracing::info!("STUB: would remove nginx config for webspace {webspace_id}");
    Ok(())
}
