//! Action-template endpoints: list/inspect the YAML templates baked into the
//! binary (see `actions/` + `build.rs`), start/observe runs on the durable
//! queue, and resolve id-picker options for the run form.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};
use uuid::Uuid;

use dioxus::prelude::*;
use plan_ai_actions::report::{RunLogEvent, RunReport, RunStatus};
use plan_ai_actions::spec::{IdOption, TemplateSpec};
use plan_ai_api_mcp_macros::api_mcp_dioxus_server;

#[cfg(feature = "server")]
use crate::server_pool;
#[cfg(feature = "server")]
use crate::web::user::{current_user, principal_from, to_serverfn};
#[cfg(feature = "server")]
use plan_ai_api_mcp::{ApiError, Principal};

// Generated by build.rs: ACTION_TEMPLATES: &[(&str, &str)] (name, yaml).
#[cfg(feature = "server")]
include!(concat!(env!("OUT_DIR"), "/actions_gen.rs"));

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
pub struct ActionTemplateRow {
    pub name: String,
    pub description: String,
    pub num_inputs: u32,
    pub num_steps: u32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, schemars::JsonSchema)]
pub struct ActionTemplateListInput {}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
pub struct ActionTemplateGetInput {
    /// Template name (the `actions/` filename stem).
    pub id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
pub struct ActionTemplateData {
    pub name: String,
    pub description: String,
    pub yaml: String,
    /// Parsed definition — the client never parses YAML itself.
    pub spec: TemplateSpec,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
pub struct ActionTemplateStartInput {
    pub id: String,
    #[serde(default)]
    pub params: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
pub struct ActionTemplateStartResult {
    pub run_id: Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
pub struct ActionTemplateRunStatusInput {
    pub id: String,
    pub run_id: Uuid,
    /// Return only events with a greater sequence number (long-poll cursor).
    #[serde(default)]
    pub after_seq: Option<u64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
pub struct ActionTemplateRunsInput {
    pub id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
pub struct ActionTemplateRunRow {
    pub run_id: Uuid,
    pub subject: String,
    pub status: String,
    pub ok: Option<bool>,
    pub created_at: String,
    pub params: serde_json::Value,
    pub report: Option<RunReport>,
    pub log: Vec<RunLogEvent>,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
pub struct ActionTemplateInputOptionsInput {
    pub id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
pub struct ActionTemplateIdOptions {
    /// input name -> picker options (only id-typed inputs with a `ref`).
    pub options: BTreeMap<String, Vec<IdOption>>,
}

/// The parsed baked-in templates, in name order.
#[cfg(feature = "server")]
pub(crate) fn baked_templates() -> &'static [(String, TemplateSpec)] {
    use std::sync::OnceLock;
    static TEMPLATES: OnceLock<Vec<(String, TemplateSpec)>> = OnceLock::new();
    TEMPLATES.get_or_init(|| {
        ACTION_TEMPLATES
            .iter()
            .map(|(name, yaml)| {
                let mut spec = plan_ai_actions::engine::parse_template(yaml)
                    .expect("baked template parses (build.rs validated it)");
                spec.name = Some((*name).to_string());
                ((*name).to_string(), spec)
            })
            .collect()
    })
}

#[cfg(feature = "server")]
fn template(name: &str) -> Result<(&'static str, &'static TemplateSpec), ApiError> {
    ACTION_TEMPLATES
        .iter()
        .zip(baked_templates())
        .find(|((n, _), _)| *n == name)
        .map(|((_, yaml), (_, spec))| (*yaml, spec))
        .ok_or_else(|| ApiError::not_found(format!("action template '{name}' not found")))
}

/// Dispatches template steps through the shared api-mcp registry as the
/// original caller — per-step org authorization applies unchanged.
#[cfg(feature = "server")]
pub(crate) struct RegistryDispatcher {
    pub pool: sqlx::PgPool,
    pub principal: std::sync::Arc<Principal>,
}

#[cfg(feature = "server")]
#[async_trait::async_trait]
impl plan_ai_actions::engine::ActionDispatcher for RegistryDispatcher {
    async fn call(
        &self,
        action: &str,
        args: serde_json::Value,
    ) -> Result<serde_json::Value, plan_ai_actions::engine::EngineError> {
        use plan_ai_actions::engine::EngineError;
        if action.starts_with("action_template_") {
            return Err(EngineError::Dispatch(
                "action_template_* tools cannot be called from a template".into(),
            ));
        }
        let registry =
            crate::api_mcp::registry().map_err(|e| EngineError::Dispatch(e.to_string()))?;
        registry
            .call_by_name(self.pool.clone(), self.principal.clone(), action, args)
            .await
            .map_err(|e| EngineError::Dispatch(format!("{action}: {e}")))
    }
}

/// Postgres implementation of the durable queue's [`RunStore`], over
/// `action_template_runs` (which doubles as run history).
#[cfg(feature = "server")]
pub(crate) struct PgRunStore {
    pub pool: sqlx::PgPool,
}

#[cfg(feature = "server")]
mod store {
    use super::*;
    use plan_ai_actions::engine::EngineError;
    use plan_ai_actions::manager::{NewRun, RunStore, StoreStatus, StoredRun};
    use plan_ai_actions::report::StepReport;
    use serde_json::{Map, Value};
    use sqlx::Row;

    fn store_err<E: std::fmt::Display>(e: E) -> EngineError {
        EngineError::Store(e.to_string())
    }

    fn row_to_run(row: &sqlx::postgres::PgRow) -> Result<StoredRun, EngineError> {
        let status = match row.get::<String, _>("status").as_str() {
            "queued" => StoreStatus::Queued,
            "running" => StoreStatus::Running,
            "ok" => StoreStatus::Ok,
            _ => StoreStatus::Failed,
        };
        let obj = |v: Value| v.as_object().cloned().unwrap_or_default();
        Ok(StoredRun {
            id: row.get("id"),
            template_name: row.get("template_name"),
            subject: row.get("subject"),
            principal: row.get("principal"),
            params: obj(row.get::<Value, _>("params")),
            status,
            next_step: row.get::<i32, _>("next_step") as u32,
            variables: obj(row.get::<Value, _>("variables")),
            steps: serde_json::from_value(row.get::<Value, _>("steps")).map_err(store_err)?,
            log: serde_json::from_value(row.get::<Value, _>("log")).map_err(store_err)?,
            report: row
                .get::<Option<Value>, _>("report")
                .map(serde_json::from_value)
                .transpose()
                .map_err(store_err)?,
        })
    }

    const RUN_COLUMNS: &str = "id, template_name, subject, principal, params, status, \
                               next_step, variables, steps, log, report";

    #[async_trait::async_trait]
    impl RunStore for PgRunStore {
        async fn enqueue(&self, run: &NewRun) -> Result<(), EngineError> {
            sqlx::query(
                "INSERT INTO action_template_runs \
                 (id, template_name, subject, principal, params, variables) \
                 VALUES ($1, $2, $3, $4, $5, $6)",
            )
            .bind(run.id)
            .bind(&run.template_name)
            .bind(&run.subject)
            .bind(&run.principal)
            .bind(Value::Object(run.params.clone()))
            .bind(Value::Object(run.variables.clone()))
            .execute(&self.pool)
            .await
            .map_err(store_err)?;
            Ok(())
        }

        async fn claim(&self) -> Result<Option<StoredRun>, EngineError> {
            let row = sqlx::query(&format!(
                "UPDATE action_template_runs SET status = 'running', updated_at = now() \
                 WHERE id = (SELECT id FROM action_template_runs WHERE status = 'queued' \
                             ORDER BY created_at LIMIT 1 FOR UPDATE SKIP LOCKED) \
                 RETURNING {RUN_COLUMNS}"
            ))
            .fetch_optional(&self.pool)
            .await
            .map_err(store_err)?;
            row.as_ref().map(row_to_run).transpose()
        }

        async fn checkpoint(
            &self,
            id: uuid::Uuid,
            next_step: u32,
            variables: &Map<String, Value>,
            steps: &[StepReport],
            log: &[plan_ai_actions::report::RunLogEvent],
        ) -> Result<(), EngineError> {
            sqlx::query(
                "UPDATE action_template_runs SET next_step = $2, variables = $3, \
                 steps = $4, log = $5, updated_at = now() WHERE id = $1",
            )
            .bind(id)
            .bind(next_step as i32)
            .bind(Value::Object(variables.clone()))
            .bind(serde_json::to_value(steps).map_err(store_err)?)
            .bind(serde_json::to_value(log).map_err(store_err)?)
            .execute(&self.pool)
            .await
            .map_err(store_err)?;
            Ok(())
        }

        async fn finish(
            &self,
            id: uuid::Uuid,
            ok: bool,
            report: &plan_ai_actions::report::RunReport,
            log: &[plan_ai_actions::report::RunLogEvent],
        ) -> Result<(), EngineError> {
            // variables scrubbed: only needed for resume, may hold secrets.
            sqlx::query(
                "UPDATE action_template_runs SET status = $2, report = $3, log = $4, \
                 variables = '{}'::jsonb, updated_at = now() WHERE id = $1",
            )
            .bind(id)
            .bind(if ok { "ok" } else { "failed" })
            .bind(serde_json::to_value(report).map_err(store_err)?)
            .bind(serde_json::to_value(log).map_err(store_err)?)
            .execute(&self.pool)
            .await
            .map_err(store_err)?;
            Ok(())
        }

        async fn load(&self, id: uuid::Uuid) -> Result<Option<StoredRun>, EngineError> {
            let row = sqlx::query(&format!(
                "SELECT {RUN_COLUMNS} FROM action_template_runs WHERE id = $1"
            ))
            .bind(id)
            .fetch_optional(&self.pool)
            .await
            .map_err(store_err)?;
            row.as_ref().map(row_to_run).transpose()
        }
    }
}

/// Copy of the validated params with secret inputs redacted — what run
/// history stores and shows.
#[cfg(feature = "server")]
fn display_params(
    spec: &TemplateSpec,
    vars: &serde_json::Map<String, serde_json::Value>,
) -> serde_json::Map<String, serde_json::Value> {
    let mut params = vars.clone();
    for (name, input) in &spec.inputs {
        if input.secret && params.contains_key(name) {
            params.insert(name.clone(), serde_json::json!(plan_ai_actions::engine::REDACTED));
        }
    }
    params
}

/// Guard: only the subject that started a run (or an admin) may observe it.
#[cfg(feature = "server")]
async fn require_run_access(
    pool: &sqlx::PgPool,
    p: &Principal,
    run_id: Uuid,
) -> Result<(), ApiError> {
    let subject = sqlx::query_scalar::<_, String>(
        "SELECT subject FROM action_template_runs WHERE id = $1",
    )
    .bind(run_id)
    .fetch_optional(pool)
    .await
    .map_err(super::internal)?
    .ok_or_else(|| ApiError::not_found("run not found"))?;
    if p.admin || subject == p.subject {
        Ok(())
    } else {
        Err(ApiError::forbidden("not your run"))
    }
}

#[api_mcp_dioxus_server(server = "list_action_templates")]
pub async fn action_template_list(
    _pool: &sqlx::PgPool,
    _p: &Principal,
    _input: ActionTemplateListInput,
) -> Result<Vec<ActionTemplateRow>, ApiError> {
    Ok(baked_templates()
        .iter()
        .map(|(name, spec)| ActionTemplateRow {
            name: name.clone(),
            description: spec.description.clone().unwrap_or_default(),
            num_inputs: spec.inputs.len() as u32,
            num_steps: spec.actions.len() as u32,
        })
        .collect())
}

#[api_mcp_dioxus_server(server = "get_action_template")]
pub async fn action_template_get(
    _pool: &sqlx::PgPool,
    _p: &Principal,
    input: ActionTemplateGetInput,
) -> Result<ActionTemplateData, ApiError> {
    let (yaml, spec) = template(&input.id)?;
    Ok(ActionTemplateData {
        name: input.id,
        description: spec.description.clone().unwrap_or_default(),
        yaml: yaml.to_string(),
        spec: spec.clone(),
    })
}

#[api_mcp_dioxus_server(server = "start_action_template")]
pub async fn action_template_start(
    _pool: &sqlx::PgPool,
    p: &Principal,
    input: ActionTemplateStartInput,
) -> Result<ActionTemplateStartResult, ApiError> {
    let (_, spec) = template(&input.id)?;
    let vars = plan_ai_actions::engine::validate_params(spec, input.params)
        .map_err(|e| ApiError::bad_request(e.to_string()))?;
    let principal = serde_json::to_value(p).map_err(super::internal)?;
    let display = display_params(spec, &vars);
    let run_id = crate::api_mcp::run_manager()?
        .enqueue(&input.id, vars, display, principal, &p.subject, spec.actions.len() as u32)
        .await
        .map_err(super::internal)?;
    Ok(ActionTemplateStartResult { run_id })
}

#[api_mcp_dioxus_server(server = "poll_action_template_run")]
pub async fn action_template_run_status(
    pool: &sqlx::PgPool,
    p: &Principal,
    input: ActionTemplateRunStatusInput,
) -> Result<RunStatus, ApiError> {
    require_run_access(pool, p, input.run_id).await?;
    // Long-poll: the server holds the request until there are new events (or
    // ~20 s pass), so the client needs no timer between polls.
    crate::api_mcp::run_manager()?
        .wait_status(input.run_id, input.after_seq, std::time::Duration::from_secs(20))
        .await
        .map_err(super::internal)?
        .ok_or_else(|| ApiError::not_found("run not found"))
}

#[api_mcp_dioxus_server(server = "execute_action_template")]
pub async fn action_template_execute(
    _pool: &sqlx::PgPool,
    p: &Principal,
    input: ActionTemplateStartInput,
) -> Result<RunReport, ApiError> {
    let (_, spec) = template(&input.id)?;
    let vars = plan_ai_actions::engine::validate_params(spec, input.params)
        .map_err(|e| ApiError::bad_request(e.to_string()))?;
    let principal = serde_json::to_value(p).map_err(super::internal)?;
    let display = display_params(spec, &vars);
    let manager = crate::api_mcp::run_manager()?;
    let run_id = manager
        .enqueue(&input.id, vars, display, principal, &p.subject, spec.actions.len() as u32)
        .await
        .map_err(super::internal)?;
    manager
        .wait_finished(run_id, std::time::Duration::from_secs(600))
        .await
        .map_err(super::internal)
}

#[api_mcp_dioxus_server(server = "list_action_template_runs")]
pub async fn action_template_runs(
    pool: &sqlx::PgPool,
    p: &Principal,
    input: ActionTemplateRunsInput,
) -> Result<Vec<ActionTemplateRunRow>, ApiError> {
    use sqlx::Row;
    let mut sql = String::from(
        "SELECT id, subject, status, params, report, log, created_at \
         FROM action_template_runs WHERE template_name = $1",
    );
    if !p.admin {
        sql.push_str(" AND subject = $2");
    }
    sql.push_str(" ORDER BY created_at DESC LIMIT 50");
    let mut query = sqlx::query(&sql).bind(&input.id);
    if !p.admin {
        query = query.bind(&p.subject);
    }
    let rows = query.fetch_all(pool).await.map_err(super::internal)?;
    rows.iter()
        .map(|row| {
            let status: String = row.get("status");
            Ok(ActionTemplateRunRow {
                run_id: row.get("id"),
                subject: row.get("subject"),
                ok: match status.as_str() {
                    "ok" => Some(true),
                    "failed" => Some(false),
                    _ => None,
                },
                status,
                created_at: row
                    .get::<chrono::DateTime<chrono::Utc>, _>("created_at")
                    .format("%Y-%m-%d %H:%M:%S")
                    .to_string(),
                params: row.get("params"),
                report: row
                    .get::<Option<serde_json::Value>, _>("report")
                    .map(serde_json::from_value)
                    .transpose()
                    .map_err(super::internal)?,
                log: serde_json::from_value(row.get::<serde_json::Value, _>("log"))
                    .map_err(super::internal)?,
            })
        })
        .collect()
}

#[api_mcp_dioxus_server(server = "action_template_id_options")]
pub async fn action_template_input_options(
    pool: &sqlx::PgPool,
    p: &Principal,
    input: ActionTemplateInputOptionsInput,
) -> Result<ActionTemplateIdOptions, ApiError> {
    use plan_ai_actions::spec::InputType;
    let (_, spec) = template(&input.id)?;
    let registry = crate::api_mcp::registry()?;
    let principal = std::sync::Arc::new(p.clone());

    let mut options = BTreeMap::new();
    for (name, ispec) in &spec.inputs {
        if ispec.ty != InputType::Id {
            continue;
        }
        let Some(resource) = &ispec.reference else { continue };
        let Some(tool) = registry.list_tool_for_resource(resource) else {
            continue; // startup validation guarantees this; stay lenient here
        };
        let rows = registry
            .call_by_name(pool.clone(), principal.clone(), &tool, serde_json::json!({}))
            .await?;
        let opts: Vec<IdOption> = rows
            .as_array()
            .map(|items| items.iter().filter_map(row_to_option).collect())
            .unwrap_or_default();
        options.insert(name.clone(), opts);
    }
    Ok(ActionTemplateIdOptions { options })
}

/// Map a list-endpoint row to a picker option: `id` + the most name-ish
/// string field.
#[cfg(feature = "server")]
fn row_to_option(row: &serde_json::Value) -> Option<IdOption> {
    let obj = row.as_object()?;
    let value = match obj.get("id")? {
        serde_json::Value::String(s) => s.clone(),
        other => other.to_string(),
    };
    let label = ["name", "title", "hostname", "email", "label"]
        .iter()
        .find_map(|k| obj.get(*k).and_then(|v| v.as_str()))
        .unwrap_or(&value)
        .to_string();
    Some(IdOption { value, label })
}
